mattermost/mattermost-plugin-github

- server/Gopkg.lock
- server/Gopkg.toml
- server/plugin.go
- server/utils.go
> Fix vulnerability notifications

- server/api.go
- server/plugin.go
- server/utils.go
- webapp/action_types/index.js
- webapp/actions/index.js
- webapp/client/client.js
- webapp/components/sidebar_buttons/index.js
- webapp/components/sidebar_buttons/sidebar_buttons.jsx
- webapp/reducers/index.js
- webapp/websocket/index.js
How this looks:
Not happy with the icon. Our current version of font-awesome only has one "merge/fork" icon.
> Adding your prs functionality to the sidebar and todo message

- server/plugin.go
> add new line

- server/api.go
- webapp/action_types/index.js
- webapp/actions/index.js
- webapp/client/client.js
- webapp/components/sidebar_buttons/index.js
- webapp/components/sidebar_buttons/sidebar_buttons.jsx
- webapp/reducers/index.js
- webapp/websocket/index.js
will be like this:
Open question for future: Maybe we can have a way to configure what to show in the sidebar 😄
> Add issues/prs Assignments to the sidebar in the ui

- server/Gopkg.lock
- server/Gopkg.toml
- server/command.go
- server/utils_test.go
- Return help message when running `/github`. Fixes #13
- Fix tests
- Update decencies
> Empty command

- README.md
For **How do I connect a repository instead of an organization?**
> Add an FAQ for README

- webapp/src/components/sidebar_buttons/sidebar_buttons.jsx
> Link "Unread messages" button to github.com/notifications

- README.md
- server/command.go
- server/subscriptions.go
- server/webhook.go
This PR adds automatic comments for pushes, branch or tag creation and deletion, issue and pull request close events, issue comments, pull request reviews and pull request review comments.
> More webhook events

- server/webhook.go
> Don't send a notification for self assigend issues

- plugin.json
- server/manifest.go
- webapp/src/manifest.js
See https://github.com/mattermost/mattermost-plugin-github/releases/tag/untagged-b157a342d678158dffa2 for changelog and assets.
Please test :wink:
> Release 0.7.0

- server/api.go
- server/configuration.go
- server/plugin.go
- server/subscriptions.go
- server/webhook.go
See https://github.com/mattermost/mattermost-plugin-jira/pull/13
> Fix config auto unmarshalling

- server/command.go
- server/subscriptions.go
> implement subscribe list

- plugin.json
- server/api.go
- server/configuration.go
- server/plugin.go
- server/subscriptions.go
- server/webhook.go
default behaviour is disabled. However, now it is possible to allow users to use private repositories as well.
fixes issue #36
> Enable private repositories

- server/api.go
Short term fix for #46 
For why this is needed see #50
> Temporarily update profile image to point to new external location

- server/subscriptions.go
The old code did only fetched the first page and not more. This PR fixes this.
> Fix paging for Subscribe Organization

- server/webhook.go
Fixes https://github.com/mattermost/mattermost-plugin-github/issues/55
> Skip notification for edit/delete of comments on issues

- plugin.json
- server/manifest.go
- webapp/src/manifest.js
@jwilander Please test when you have the time :wink:
> Bump version to 0.9.0

- plugin.json
- server/configuration.go
- server/manifest.go
- webapp/package.json
- webapp/src/manifest.js
See https://community.mattermost.com/core/pl/3ukuuy7o8pngzdgxdtaxzns1fa for context
> Point to external profile image and bump version to 0.9.1

- plugin.json
> Proposed help text update for EnablePrivateRepo setting

- README.md
1. Add an example for using `/github subscribe`
2. Break configuration steps into three sections
3. Minor updates throughout
> Updates to docs

- README.md
From https://community.mattermost.com/core/pl/36k9egjafjfi8eototdtq6ku9c
> New FAQ: How does the plugin save user data for each connected GitHub user?

- server/api.go
Ticket: https://mattermost.atlassian.net/browse/MM-16038
> MM-16038 Improving oauth connect flow.

- README.md
Feedback on how to make this more clear welcome. 
The experience is planned to improve via https://mattermost.atlassian.net/browse/MM-16147
> Update bot conversion step for admin, for 5.12

- plugin.json
Added some extra contextual info about the plugin and what it does, and how to install it, building upon previous changes by @jasonblais
> Update Header text and instructions

- README.md
> FAQ: How do I send notifications when a certain label is applied?

- README.md
Cleared up very tiny but at the same time very confusing formatting error.
> Fixed formatting error

- webapp/src/components/sidebar_right/github_items.jsx
Ticket: https://mattermost.atlassian.net/browse/MM-17864
Screenshot:
> MM-17864 - Updating github items css

- server/template.go
- server/template_test.go
* changed template logic to include comments
* updated test cases to check for comments
Fixes https://github.com/mattermost/mattermost-server/issues/12400
> MM-18877 Add comments to pull request notifications

- server/template.go
- server/template_test.go
> Add PR and Issue Title in Notification DMs

- webapp/src/components/post_menu_actions/attach_comment_to_issue/attach_comment_to_issue.jsx
Ticket: https://mattermost.atlassian.net/browse/MM-19494
> MM-19494 - Updating styling for github icon

- server/template.go
- server/template_test.go
Fix https://github.com/mattermost/mattermost-plugin-github/issues/152
It's my first contribution, so even though it's not too complex, any comment would be appreciated.
Thanks!
> Include comments in notifications for approval / changes requested

- webapp/src/components/sidebar_buttons/sidebar_buttons.jsx
Ticket: https://mattermost.atlassian.net/browse/MM-20306
> MM-20306 - Fixing header button spacing

- server/webhook.go
- S1021: should merge variable declaration with assignment on next line.
- S1009: should omit nil check; len() for nil slices is defined as zero.
> Fix gosimple using using golangci-lint

- webapp/package-lock.json
- webapp/package.json
- webapp/src/client/client.js
- webapp/webpack.config.js
This PR updates the `mattermost-redux` dependency to handle potential csrf issues.
https://mattermost.atlassian.net/browse/MM-18640
- Set `ServiceSettings.ExperimentalStrictCSRFEnforcement` to true in the server's config.json
- Verify that the "Attach Comment to Issue" feature works
> [MM-18640] Update mm redux for csrf

- plugin.json
- server/manifest.go
- webapp/src/manifest.js
Bump version to 0.13.0 
https://community-release.mattermost.com/core/pl/an4iq9yng7grdx5akfe5z59k7a
> Bump version to 0.13.0

- server/plugin.go
Hello, while I was searching for an issue to maybe work on I found this little quick win. :slightly_smiling_face: 
This PR fixes some typos in the strings from the `GetToDo` function in `server/plugin.go`.
https://mattermost.atlassian.net/browse/MM-22285
> [MM-22285] Fix typos on GetToDo message strings

- go.sum
- server/command.go
- server/command_test.go
Adds validation to prevent subscription to a repo with invalid feature(s)
Fixes https://github.com/mattermost/mattermost-plugin-github/issues/165
> Fix #165: Validate features before subscribing

- server/command.go
- server/subscriptions.go
- server/subscriptions_test.go
- server/template_test.go
- webapp/package.json
- webapp/src/components/github_issue_selector.jsx
- webapp/src/index.js
Result for /github subscribe list now shows flags
Fixes https://github.com/mattermost/mattermost-plugin-github/issues/186
> Result for /github subscribe list now shows flags

- webapp/src/components/post_menu_action/create_issue/create_issue.jsx
This fixes the linting error from `make check-style`
> fix linting error

- server/api.go
- webapp/src/components/modals/create_issue/create_issue.jsx
Note this PR is for the create-issue Feature branch, not master.
This ticket adds a response post to a thread if a GitHub issue is created from the post.
https://github.com/mattermost/mattermost-plugin-github/issues/219
> [GH-219] After creating issue, reply to post in MM with the Github link

- plugin.json
- server/manifest.go
- webapp/src/manifest.js
Bump version to 0.14.0
Fixes https://github.com/mattermost/mattermost-plugin-github/issues/195
> Bump version to 0.14.0

- .golangci.yml
- Makefile
- server/api.go
- server/command.go
- server/template_test.go
- server/webhook.go
This PR adds the golangci.yml file and fixes the pending issues remaining for it to pass.
> Added golangci.yml file to repo

- go.sum
- webapp/src/action_types/index.js
- webapp/src/actions/index.js
- webapp/src/components/github_repo_selector.jsx
- webapp/src/components/github_repo_selector/github_repo_selector.jsx
- webapp/src/components/github_repo_selector/index.js
- webapp/src/components/modals/create_issue/create_issue.jsx
- webapp/src/components/react_select_setting.jsx
- webapp/src/components/setting.jsx
- webapp/src/components/validator.js
- webapp/src/reducers/index.js
This ticket resolves the remaining issues for the create-issue-modal feature that will be added to the master branch.  Please see the linked GH tickets in the Ticket Link Section.
Here is the commit message which lists the components that were added to the modal, as well as refactoring items. (ie. GitHubRepoSelector now uses ReactSelectSetting component)
**GitHubRepoSelector component**
- now uses ReactSelectSetting component
- made into its own component so it can be shared with the attach
comment to issue modal, which needs a repo selector
- uses the new validator component for validation in the
ReactSelectSetting component
- getReps()
- called only once when componentDidMount is called
- performs the client call to get the repos
- pulled this.state variables initialization into its own …
> Complete the Create Issue Modal issues

- server/command.go
- server/plugin.go
- webapp/package-lock.json
- Split ExecuteCommand into separate command handlers.
- Made map of [command][handler]
- Resolved some unhandled error warnings
Fixes https://github.com/mattermost/mattermost-plugin-github/issues/211
> Refactor command handlers

- webapp/src/actions/index.js
- webapp/src/components/sidebar_buttons/index.js
- webapp/src/components/sidebar_right/index.jsx
- webapp/src/components/user_attribute/index.js
- webapp/src/websocket/index.js
Replaced hard coded plugin id with manifested variable
Fixes https://github.com/mattermost/mattermost-plugin-github/issues/238
> Replaced hard coded plugin id with manifested variable

- go.mod
- go.sum
- server/api.go
- server/api_test.go
- server/plugin.go
- server/testutils/http.go
- server/util/util.go
- Added mux router 
- Deleted repetitive code and added middleware
Fixes https://github.com/mattermost/mattermost-plugin-github/issues/246
> Added gorilla mux router

- server/api.go
- server/configuration.go
- server/plugin.go
- server/subscriptions.go
- server/template.go
- server/utils.go
Every error returned from a function is now wrapped with an appropriate message.
Fixed KVSet return error being ignored
https://github.com/mattermost/mattermost-plugin-github/issues/254
> Errors properly wrapped

- README.md
PR to add release version and Help Wanted Badges to the readme
n/a
> Add release version and HW badges

- README.md
- server/template.go
- server/template_test.go
- server/webhook.go
- Update readme to order events in the same way as the web UI
- Change create event messages to be consistent with other messages
New:
Follow up on https://github.com/mattermost/mattermost-plugin-github/issues/307
> Improve create events documentation and wording

- webapp/src/components/link_tooltip/link_tooltip.jsx
- webapp/src/components/link_tooltip/tooltip.css
- webapp/src/utils/styles.js
This PR links the user's theme to the tooltip so it get's the proper style.
Fixes #294
> [GH-294] link user's theme to tooltip

- server/template.go
- server/template_test.go
New lines in body used to break quoting, now it doesn't!
Tests updated to reflect.
Fixes #281 
The `Difficulty/3:Hard` label is making me feel like I might have misunderstood the problem. If so, I'll correct it. Thanks!
> Quote newlines within body

- server/plugin/api.go
- Removed commented text present in body of PR/Issue that was displayed in the tooltip (on hovering over PR/issue link) by using `mdCommentRegex`, prepared from the regex for 'comments in markdown' available in `template.go`[1].
[1] [https://github.com/mattermost/mattermost-plugin-github/blob/master/server/plugin/template.go#L13-L28](https://github.com/mattermost/mattermost-plugin-github/blob/master/server/plugin/template.go#L13-L28)
Fixes https://github.com/mattermost/mattermost-plugin-github/issues/312
> Removed commented text in Tooltip link body

- server/plugin/command.go
I'm 1/5 on the wording. 
Fixes https://github.com/mattermost/mattermost-plugin-github/issues/342
> Add warning when subscribing to a private repository

- server/plugin/template.go
- server/plugin/template_test.go
Display labels and assignee when creating new Issue or PR.
Fixes https://github.com/mattermost/mattermost-plugin-github/issues/257
> [GH-257] Display labels and assignee on new issues and PRs

- server/plugin/command.go
Fixes https://github.com/mattermost/mattermost-plugin-github/issues/364
> Post command response in RHS if triggered from there

- plugin.json
- server/plugin/manifest.go
- webapp/src/manifest.ts
Let's cut an rc and test it on community.
Part of https://github.com/mattermost/mattermost-plugin-github/issues/304
> Release v2.0.0-rc1

- plugin.json
- server/plugin/manifest.go
- webapp/src/manifest.ts
Add `release_notes_url`
Need because of https://github.com/mattermost/mattermost-marketplace/pull/100
> Add release_notes_url

- server/plugin/command.go
- server/plugin/subscriptions.go
- server/plugin/template.go
- server/plugin/webhook.go
If you are subscribed to only when issues are created, you do not receive notifications for other cases.
Fixes https://github.com/mattermost/mattermost-plugin-github/issues/390
> Separate Post for Creating Issues

- webapp/src/components/link_tooltip/link_tooltip.jsx
This fixes a regression introduced in https://github.com/mattermost/mattermost-plugin-github/pull/293.
Fixes https://github.com/mattermost/mattermost-plugin-github/issues/412
> Fix icons in link tooltip

- server/plugin/manifest.go
- webapp/src/manifest.ts
Run `make apply`
Follow up on https://github.com/mattermost/mattermost-plugin-github/pull/417
> Make apply

- server/plugin/api.go
https://mattermost.atlassian.net/browse/MM-34892
> Fixed setting Mattermost-Plugin-ID header

- server/plugin/plugin.go
- webapp/package-lock.json
Use `AuthStyleInHeader` to make client_id/client_secret to be passed in the HTTP header.
https://github.com/golang/oauth2/blob/2e8d9340160224d36fd555eaf8837240a7e239a7/internal/token.go#L174
#431, https://mattermost.atlassian.net/browse/MM-34646
> Use HTTP header for app authentication

- plugin.json
- server/plugin/manifest.go
- webapp/src/manifest.ts
Release v2.0.1
Part of https://github.com/mattermost/mattermost-plugin-github/issues/435
> Release v2.0.1

- webapp/src/client/client.js
- webapp/src/index.js
- webapp/src/selectors.js
Added Site Url for call from webapp
ticket here
https://github.com/mattermost/mattermost-plugin-github/issues/332
>  mm 332 - Use SiteURL for all calls from the webapp

- webapp/src/index.js
Fixed issue where we made HTTP requests prior to fetching URL Details which lead to all HTTP being made to wrong URLs
ticket here
https://github.com/mattermost/mattermost-plugin-github/issues/477
> [mm 477] Master branch no longer shows UI elements when user connects to GitHub fixes #477

- .circleci/config.yml
Configured `plugin-ci/test' for github
Ticket here
Fixes #502
> [issue 502] Cross-plugin task: Enable the CircleCI "test" job in each plugin repo that has a webapp plugin #502

- server/plugin/api.go
- server/plugin/plugin.go
fixed the logic of complete the oauth complete redirect
Fixes #509
> [mm 509] Resolve OAuth bug with KVStore #509

- server/plugin/template.go
- server/plugin/webhook.go
- Add user/users as assignee to an issue
- Comment on the issue
- Assignee's receive direct message from Bot on Mattermost
Fix #391 
#391
> Assignee of issue/PR receive notifications for new comments

- server/plugin/command.go
- server/plugin/subscriptions.go
- server/plugin/utils.go
- server/plugin/webhook.go
Revert "MM  418  - Add --exclude option to subscriptions command #418 (#457)
This reverts commit 943ee2f74eae5f79a2820df04d43497b9956a62a.
I made this PR so it will be easy to follow through with the potential decision of reverting the `exclude` feature
> Revert "MM  418  - Add --exclude option to subscriptions command" (#457)

- go.mod
- go.sum
- server/plugin/flows.go
> Updated to the latest flow library

- server/plugin/api.go
- server/plugin/configuration.go
- server/plugin/plugin.go
- webapp/src/action_types/index.js
- webapp/src/actions/index.js
- webapp/src/client/client.js
- webapp/src/components/sidebar_header/index.js
- webapp/src/components/team_sidebar/index.js
- webapp/src/index.js
- webapp/src/reducers/index.js
- webapp/src/selectors.js
- webapp/src/websocket/index.js
The websocket handler was updated in https://github.com/mattermost/mattermost-plugin-github/pull/515.
Fixes https://github.com/mattermost/mattermost-plugin-github/issues/530
Fixes https://github.com/mattermost/mattermost-plugin-github/issues/536
> Fix JS error on dis/connect

- server/plugin/webhook.go
Fixes https://mattermost.atlassian.net/browse/MM-42096
> Fix MM-42096

- plugin.json
Release Bump v2.1.1
https://github.com/mattermost/mattermost-plugin-github/issues/553
> Release bump v2.1.1

- Makefile
> Add --verbose flag to npm install

- Makefile
- server/plugin/api.go
More `context` in the ticket linked below
Fixes https://github.com/mattermost/mattermost-plugin-github/issues/578
> Increase request timeout for context used for plugin http endpoints

- plugin.json
- https://github.com/mattermost/mattermost-plugin-github/pull/555
- https://github.com/mattermost/mattermost-plugin-github/pull/579
https://github.com/mattermost/mattermost-plugin-github/issues/580
> Release bump v2.1.2

- Makefile
- plugin.json
- https://github.com/mattermost/mattermost-plugin-github/pull/614
https://github.com/mattermost/mattermost-plugin-github/issues/615
> Release 2.1.4

- .github/workflows/cd.yml
- .github/workflows/ci.yml
- webapp/package-lock.json
- webapp/package.json
This also includes the fix from https://github.com/mattermost/mattermost-plugin-antivirus/pull/39
None
> Update GitHub actions workflow

- plugin.json
> bump v2.1.6

- README.md
Added explanation for /setup command
Fixes #655
> Added explanation for /setup command

- go.mod
- go.sum
Make use of https://github.com/mattermost/actions/pull/13
> Update go version to 1.21

- .github/workflows/issue_add.yml
Added [issue_add.yml](https://gist.github.com/mickmister/9ded832b3f26bb7bc69e0198d8b53ebe#file-plugin-install-gh-artifact-sh) to automate adding issues to GitHub board.
> [issue_add.yml]: Added issue_add.yml to automate adding issues to GitHub board.

- server/plugin/configuration_test.go
Fixes: https://github.com/mattermost/mattermost-plugin-github/actions/runs/7263964827/job/19790433763?pr=725
> [MM-42] Fix ci error: implicit memory aliasing

- CODEOWNERS
- README.md
Adding myself as a code owner to the GitHub plugin to surface new PRs as review requests
> Update CODEOWNERS to include mickmister

- server/plugin/api.go
- server/plugin/api_test.go
returning proper JSON response from APIs
Fixes https://github.com/mattermost/mattermost-plugin-github/issues/794
> [MM-794]: Returning proper JSON response from APIs

- webapp/src/components/link_tooltip/link_tooltip.jsx
- webapp/src/components/link_tooltip/tooltip.css
Display the PR/issue author in the plugin tooltip
Fixes https://github.com/mattermost/mattermost-plugin-github/issues/401
> [MM-401]: Added pr/issue opened by in tooltip modal

- webapp/src/components/sidebar_right/github_items.tsx
Make username clickable in RHS PRs/Issues
Fixes https://github.com/mattermost/mattermost-plugin-github/issues/408
> [MM-408]: Made username clickable in RHS PRs/Issues

- webapp/package-lock.json
- webapp/package.json
- webapp/src/components/modals/create_issue/__snapshots__/create_issue.test.jsx.snap
- webapp/tests/setup.tsx
Add license header to setup.tsx
NONE
> Add license header to setup.tsx

- webapp/src/components/github_repo_selector/github_repo_selector.jsx
Fix the issue of create issue modal not working with an invalid organisation
Fixes https://github.com/mattermost/mattermost-plugin-github/issues/898
> [MM-898]: Fix issue of create issue modal not working with invalid organisation

- server/plugin/api.go
Fix the issue of the repository not listing when the organisation lock has one invalid organisation among the valid organisation list for `Attach to issue` and `Create issue` modal
Fixes https://github.com/mattermost/mattermost-plugin-github/issues/901
> Fix issue of repo/issue not listing when org lock has one invalid org among valid org list

- server/plugin/plugin.go
Add plugin bot id check to reaction mapper
> Add plugin bot id check to reaction mapper
