mattermost/mattermost-plugin-github

server/command.go

in the `/github me` instead of seeing this output with the underline in the middle of the image and the text: 
we can have this:

small output fix for /github me command

---

README.md
plugin.json
server/api.go
server/plugin.go

This is a follow-up to #40 to send a message to users who had previously connected to the GitHub plugin, letting them know to reconnect their accounts to use private repos.
I also updated the README and the setting help text.
FYI @zetaab

Send message to users that need to reconnect to access private repos

---

webapp/src/components/user_attribute/index.js
webapp/src/components/user_attribute/user_attribute.jsx

Url shown in profile hover always points to github.com/\<username\> instead of \<enterprise-url\>/\<username\>
This fixes the url to point to correct address
Fixes #42

Fix profile hover url when enterprise url is set

---

.circleci/config.yml

Adding a functionality to deploy to GH when we tag a release

deploy to GH when tag a release

---

server/webhook.go

Fix #48: Use IssueCommentEvent's action in post msg

---

server/command.go
server/subscriptions.go
server/utils.go

The previous implementation would require paging through all the repositories of an organization and creating a subscription for each one, at the time the org was subscribed to. This worked OK but by just storing a single subscription for the entire org instead we can reduce a lot of what we're storing and get rid of the paging hits against the GH API.
The new implementation also has the major benefits of automatically picking up on new repositories added to the organization (since the webhook is org wide already) and not requiring unsubscribing from each and every repository when you want to unsubscribe a channel from an organization.

Update organization subscription implementation

---

README.md

We have a customer who is unable to deploy the GitHub plugin in our HA environment due to lack of documentation.
Resolving administrative challenges is in the EXT near term roadmap, however, in the meantime I'd propose documenting these two notes for HA installs.
Feedback welcome.

Add install notes in HA

---

README.md

1. Add note about connecting your account to access features as an end user
- Feedback on how to make this more obvious is welcome
2. Fix section headers in FAQ

Clarify how to access features as end user

---

server/api.go
server/plugin.go

Issue : #90
Current:
Currently the daily reminder is always send even if there is nothing the user has missed. 
PR: 
Adds a check before sending the daily update. Now there either has to be an unread message, a pull request needing reviewing, an open pull request or a new assignment. 
If nothing is found to report there will be no daily update.

GH-90 Added checking for updates before sending daily update

---

README.md

Two people today had issues with this README 
- (while screensharing) one tried to copy-paste the provided webhook and OAuth URLs, but had trouble because they are formatted as links with quotation marks. Updated to use in-line code formatting instead
- both missed "Content Type" value in configuring webhook
- one missed the correct authorization callback URL
PM review: @aaronrothschild tagging you for review, so that you can help review the proposed changes

README update: format setting config for better usability

---

server/utils.go
server/utils_test.go

I've had a notification sitting unread for a while that linked out to https://github.com/mattermost/mattermost-server/commits/cc6c385d3e8903546fc6fc856bf468ad09b70913, but never marked the notification as read. Digging through the code, I discovered `fixGithubNotificationSubjectURL` and the need to do the same for `/commits/`. Tested locally, which fixed my notification issue, then added that very notification as a test case.

extend fixGithubNotificationSubjectURL to commits

---

plugin.json

In response to https://github.com/mattermost/mattermost-plugin-github/issues/94
@aaronrothschild would be curious to hear your thoughts on other options, e.g. we could link to docs from the Introduction page, or incorporate some of the steps directly in there.

Update GitHub plugin introduction with authorization callback URL

---

server/api.go

Update server to send down an `html_url` for use in linking notifications in the RHS.

link notifications in rhs

---

server/plugin.go

Right now, the reminder DM (or `/github todo`) shows just the URLs. This PR adds additionaly a title of the PRs and Issues , making the list easier to read.

added titles to todo elements

---

server/webhook.go

- Provide a more clear error message when the wrong content type is selected for a webhook
- Update the server log error message to state GitHub webhook content type should be set to "application/json"
- Fail the request with a proper status code so that the webhook shows up as failed on GitHub
Fixes https://github.com/mattermost/mattermost-plugin-github/issues/95

updated webhook log when webhook type is not application/json

---

go.mod
go.sum

go mudule unable to access git.apache.org as it is timing out. Replacing it with github.com for thrift.
https://github.com/mattermost/mattermost-server/issues/12125

replacing apache.com/thrift with github.com to solve network issue when building

---

go.mod
plugin.json
server/manifest.go
webapp/src/manifest.js

Bumping version to v0.12.0 to cut a new release, with the primary purpose of including the recent `plugin.json` metadata changes for programmatic consumption by the marketplace.

Bump version to 0.12.0

---

server/template.go
server/template_test.go

Some few changes on templates `pullRequestReviewNotification`, `commentAuthorPullRequestNotification` and `commentAuthorIssueNotification` added full comment link instead of using the main object that reference the comment
Had to created some new template to handle these changes correctly:
`reviewRepoPullRequest`: link of the review object
`commentRepoIssue`: link of the comment object
Changed unit tests according to these changes
Fixes #142

[MM-19443] Link to the comment that cause the notification

---

Makefile
plugin.json
server/configuration.go
server/main.go
server/permalinks.go
server/permalinks_test.go
server/plugin.go
server/utils.go
server/utils_test.go

For every message we now hook into the MessageWillBePosted event, and check
if it contains a permalink to a Github file.
If yes, we parse out the link, and make an API call to the Github contents API.
Get the file contents and filter out the required lines given in the permalink anchor.
Then we construct a code block in markdown and replace the original string.
Added a config key to gate this feature.
Screenshots:
With config disabled:
After enabling it:
The newly formed hyperlink is a link to the original permalink
Config setting:
[MM-18880](https://mattermost.atlassian.net/browse/MM-18880)
Fixes #128

MM-8880: Show code block previews of Github permalinks

---

server/api.go

Summary:
Fix "octopus icon randomly changes where it points to"
Issue link:
Fixes https://github.com/mattermost/mattermost-plugin-github/issues/139

[GH-139] octopus icon randomly changes where it points to

---

server/template.go
server/template_test.go

- Removes timestamps from posts since the mattermost app already shows a timestamp when message is posted.
- Since the time shown by the github plugin is always UTC it is confusing since it is in a different timezone
- The consensus from this issue here https://github.com/mattermost/mattermost-plugin-github/issues/109 seemed to be to remove the timestamp entirely 
Fixes https://github.com/mattermost/mattermost-plugin-github/issues/109
Heres what it currently looks like 
Heres what the proposed changes look like

Remove timestamps and duplicate url from templates

---

build/manifest/main.go
go.mod
go.sum
server/api.go
server/command.go
server/configuration.go
server/main.go
server/permalinks_test.go
server/plugin.go
server/subscriptions.go
server/template.go
server/template_test.go
server/webhook.go

- Update Mattermost dependency on all plugins to 5.18
- Update MM import path using `find . -name "*.go" -type f | xargs sed -i -e 's/github.com\/mattermost\/mattermost-server\//github.com\/mattermost\/mattermost-server\/v5\//g'`
- Run `go mod tidy`
- Update other dependencies
https://mattermost.atlassian.net/browse/MM-21354

Bump Mattermost to 5.18

---

README.md
server/command.go
server/plugin.go
server/subscriptions.go
server/utils.go
server/utils_test.go
server/webhook.go

- Command: we iterate through every parameter, identifying if it's a "feature" or a "flag" (for this purpose, some helper functions have been included in "utils")
- Subscription: a new struct for flags has been created.
- Plugin: a new method isUserOrganizationMember has been added.
- Webhook: a new method excludeConfigOrgMember has been included. It's responsible for fetching configuration and creating the GitHub client.
I have created two different methods so isUserOrganizationMember could be reused without any links to the purpose of this task.
Thanks!
Fixes https://github.com/mattermost/mattermost-plugin-github/issues/125

Exclude organization members feature

---

server/template.go
server/template_test.go

This PR adds a function to the template generation process that matches all Github usernames and replaces them with their assigned Mattermost usernames, if any.
The regular expression to match the GitHub usernames is the following:
```
(^|[^_\x60[:alnum:]])(@[[:alnum:]](-?[[:alnum:]]+)*)
\___________________/ \__________/\_______________/
(1)             (2.1)           (2.2)
\_____________________________/
(2)
```
- The first matching group, (1), matches the beginning of the line or a character that is allowed to precede a GitHub username; i.e., any character different than underscore, backtick or an alphanumeric character.
- The second matching group, (2), wraps the matched GitHub username. Notice that there is no limit on its maximum length (39 at the moment), but in the rare case that …

GH-176 Replace GitHub usernames in body of notifications

---

server/template.go
server/template_test.go

This PR makes it such that '>' is not displayed if the review body is empty
Resolves #185

Fix template so `>` is not displayed if review body is empty

---

server/command.go
server/template_test.go
webapp/package.json
webapp/src/components/github_issue_selector.jsx
webapp/src/index.js

Replace `Github` with `GitHub` everywhere in the code
https://mattermost.atlassian.net/browse/MM-22697
Fixes https://github.com/mattermost/mattermost-plugin-github/issues/175

[MM-22697] Replace Github with GitHub everywhere

---

server/plugin.go

https://github.com/mattermost/mattermost-plugin-github/pull/154 did add a feature flag `--exclude-org-member` to subscriptions, which allows to ignore events from organization members. Currently, the oauth scope doesn't include information about the membership of the user. This PR fixes it by broadening the scope.
To apply this fix to a given subscription the user who created it has to disconnect and reconnect the MM account to GitHub.
I've tested my changes with ngrok and a test organisation.
1. Create two users and connect them both to the github via `github connect`
2. Create an organization ORG and let both users join it
3. Make sure organization visibility is set to "private" for user B
4. As user A create a subscription to ORG using `--exclude-org-member`
5. As user B create an …

Require read:org scope for OAuth connect

---

webapp/src/components/github_repo_selector.jsx
webapp/src/components/modals/create_issue/create_issue.jsx

This PR resolves two issues with the new Create Issue Modal where field validation is necessary.  
1) #216 No validation if Title is left empty
2) #215 Submit hangs if the repository is left empty
Fixes #216 
Fixes #215

Add user validation for repo and title fields

---

README.md

This PR adds the create issue and attach to issue post-action options to the features section of the README
Fixes #220

[GH-220] Add attach and create post action features to the README

---

server/configuration.go

Drop PluginsDirectory from config as it's not longer needed.
Fixes https://github.com/mattermost/mattermost-plugin-github/issues/249

Drop PluginsDirectory from config

---

server/api.go

* Attaching a message to an issue links to GitHub account, not MM account
- Instead of using the MM username, the username on GitHub is used. 
- If the user whose message is attached is not connected to GitHub, then the MM username is used
* Added permalink to Message in reply, which is given after a user attaches a message to a GitHub issue
Fixes https://github.com/mattermost/mattermost-plugin-github/issues/253

Attaching a message to an issue links to GitHub account, not MM account

---

server/api.go
webapp/src/components/sidebar_right/github_items.jsx
webapp/src/components/sidebar_right/index.jsx

Indicate on RHS, if the PR as a conflict. Please note that the PR status is always `pending` if there is a conflict. But that issue was present before this changes and is unrelated.
Fixes https://github.com/mattermost/mattermost-plugin-github/issues/225

Indicate if a PR has a conflict

---

webapp/src/components/post_menu_action/create_issue/create_issue.jsx

0/5, is it possible to have a build check of some kind that detects an incorrect capitalization in future?

Fix Github > GitHub capitalization error

---

webapp/src/components/link_tooltip/tooltip.css

**Before:**
**After:**
https://github.com/mattermost/mattermost-plugin-github/issues/330

Break text in link tooltip

---

server/plugin/command.go
server/plugin/command_test.go

This PR will update the command parser such that it will skip whitespaces in two double-quotes. This will fix the related bug by protecting the integrity of multi-word labels such as "Help Wanted".
Fixes #283

[GH-283] Fix parsing multi-word labels in subscription command

---

server/plugin/template.go

Improve documentation for label subscribe feature to make clear that only one label should be provided.
The PR also adds a missing new line.
Fixes https://github.com/mattermost/mattermost-plugin-github/issues/347

Improve label subscribe documentation

---

server/plugin/api.go
server/plugin/api_test.go

Add recovery middleware to avoid crashing the whole plugin if one API call panics.
Credit for the code goes to @agnivade 
Fixes https://github.com/mattermost/mattermost-plugin-github/issues/348

Add recovery middleware

---

server/plugin/api.go

- Checks whether pointer to the body of PR/Issue is `nil` before accessing it to avoid panic.
- I have assumed that `result` obtained by calling `Get()` on PR/Issue is never `nil` as other functions do not check this condition (Reference: https://github.com/mattermost/mattermost-plugin-github/blob/master/server/plugin/api.go#L489).
Extension to the PR https://github.com/mattermost/mattermost-plugin-github/pull/326 that fixes https://github.com/mattermost/mattermost-plugin-github/issues/312

Avoided panic on empty body of PR and Issue

---

plugin.json
server/plugin/api_test.go
server/plugin/configuration.go
server/plugin/permalinks.go
server/plugin/plugin.go

Add a dropdown to the system console to set the level for which code preview is enabled. By default, it's enabled for public repos.
Installations that had Code Preview enabled before will now only have it enabled for public repo. That seams like a fine solution as the security implications were not clear for admin in the past.
Fixes https://github.com/mattermost/mattermost-plugin-github/issues/323

Add dropdown setting for Code Preview

---

webapp/src/components/sidebar_right/github_items.jsx

This PR improves the them awareness of the RHS by using theme defined colors instead of pre defined ones. It also improves the visual appeal by reducing the number of colors used.
The changes are:
- Remove opacity from Milestone icon
- Use theme colors of PR status icons
- Use `dndIndicator` color for merge conflict icon
- Use `dndIndicator` color for changes requested icon
| Before  | After           |
|---------|-----------------|
| ![Screenshot from 2020-09-11 11-15-49](https://user-images.githubusercontent.com/16541325/93178160-20456400-f734-11ea-91e9-87ee5a51c56c.png) | ![Screenshot from 2020-09-11 11-16-40](https://user-images.githubusercontent.com/16541325/93178179-28050880-f734-11ea-815e-9ba1e214845b.png) |
| ![Screenshot from 2020-09-11 …

Make RHS more theme aware

---

webapp/src/components/link_tooltip/link_tooltip.jsx

Make use of the `show` prop added in https://github.com/mattermost/mattermost-webapp/pull/6492 by only rendering the tooltip on hover. This means data is not longer pre-fetched. Therefore a small delay is visible when hovering. Please note, on re-hovering the link the tooltip is shown imminently. Switching channel caused the data to be lost and it's required to fetch is again. I opted for this approach because storing the data in redux would mean that we would have to clean it up from time to time and it's hard to figure out what data should be cleaned up.
The change is backward compatible to 
I did also simplify the existing code a bit.
https://mattermost.atlassian.net/browse/MM-28591

Only render tooltip on hover

---

server/plugin/command.go
server/plugin/template.go

Make users aware that muting a user only blocks notifications for comments on PRs and issues
https://github.com/mattermost/mattermost-plugin-github/pull/354#issuecomment-694212719

Make mute feature more clear

---

webapp/src/components/link_tooltip/link_tooltip.jsx

For links like https://github.com/mattermost/mattermost-plugin-agenda/pull the tooltip should not try to fetch the PR/issue details.
https://mattermost.atlassian.net/browse/MM-28543

Don't try to fetch PR/issue details for malformed link

---

webapp/src/components/sidebar_right/github_items.jsx

| Before  | After           |
|---------|-----------------|
| ![Screenshot from 2020-09-25 20-29-24](https://user-images.githubusercontent.com/16541325/94303848-c54f1080-ff6e-11ea-9dc2-cc511298d11d.png) | ![Screenshot from 2020-09-25 20-26-52](https://user-images.githubusercontent.com/16541325/94303858-cb44f180-ff6e-11ea-99ff-db6210b2a9be.png) |
| ![Screenshot from 2020-09-25 20-29-49](https://user-images.githubusercontent.com/16541325/94303870-d435c300-ff6e-11ea-8971-36aadce5cbd8.png)| ![Screenshot from 2020-09-25 20-27-08](https://user-images.githubusercontent.com/16541325/94303875-d7c94a00-ff6e-11ea-8624-5aee463c8334.png) |
Fixes https://github.com/mattermost/mattermost-plugin-github/issues/375

Use issue icon in RHS

---

server/plugin/webhook.go

This PR fixed double messaging when an issue gets labeled in the process of creating it
This PR is linked with the issue #389

Fix issue labeling double message

---

server/plugin/plugin.go
server/plugin/subscriptions.go

The pull request adds a check to fail github subscription when flag `--exclude-org-member` is set, but organization is not locked.
For testing, I created a new org and a repo inside that org and tried subscribing to it with/without flag. 
Fixes https://github.com/mattermost/mattermost-plugin-github/issues/214

Subscription using --exclude-org-member flag should fail without locked org

---

server/plugin/api.go

Originally the handler for 410 Gone (Issues not enabled on a repository) was placed after the generic error handling code, meaning it would never be called.

[FIX] Handle Issue Creation failures in the correct place

---

server/plugin/plugin.go
server/plugin/webhook.go

`CreatePost` should never fail. This PR adds the post to the log output. It doesn't look pretty, as it's a plain go struct dump (Post don't have a `String()` method), but for debugging it does the trick.
Part of https://github.com/mattermost/mattermost-plugin-github/issues/405

Log post when CreatePost fails

---

plugin.json
server/plugin/api.go
server/plugin/configuration.go
server/plugin/manifest.go
webapp/src/actions/index.js
webapp/src/client/client.js
webapp/src/index.js
webapp/src/manifest.ts

Mattermost github plugin issue - #384

Added setting to hide/show left sidebar github buttons

---

README.md

Documentation for:
- https://mattermost.atlassian.net/browse/MM-31348
Updated:
- Audience section to include MM staff as a key audience for this page
- Updated Configuration > Step 1 to clarify steps for MM users
- Updated Configuration > Step 2 & Step 3 to clarify steps completed by system admins

MM-31348 Clarify Mattermost GitHub Plugin setup

---

server/plugin/api.go

The caller of `createContext` needs to cancel it instead of `createContext` itself.
https://mattermost.atlassian.net/browse/MM-36742
Fixes https://github.com/mattermost/mattermost-plugin-github/issues/451

[MM-36742] Fix immediately expiring request context

---

webapp/src/components/sidebar_right/github_items.tsx

Adds the following time field in the list of unread messages in the RHS
https://github.com/mattermost/mattermost-plugin-github/issues/182

mm-182 - adds a {time} ago field in the list of unread messages pane. 

---

server/plugin/command.go
server/plugin/plugin.go

handled unconfigured state and allowed user to start the plugin with useful message if not configured
ticket here
https://github.com/mattermost/mattermost-plugin-github/issues/432

Mm 432 - Handle "unconfigured" state of plugin gracefully

---

server/client/client.go
server/plugin/configuration.go

Removed trailing spaces from clientid , accesstoken and orgname while geting the configuration
ticket here
https://github.com/mattermost/mattermost-plugin-github/issues/461

mm-461 Trailing space in my access_token causes uninformative error message fixes #461

---

webapp/src/components/link_tooltip/tooltip.css

Updates css to fix cutoff words in word wrap.
Fixes: #455

Fix cutoff words in word wrap

---

server/plugin/api.go
server/plugin/command.go
server/plugin/mm_34646_token_refresh.go
server/plugin/plugin.go
server/plugin/webhook.go

Hopefully fixes #431 and https://mattermost.atlassian.net/browse/MM-34646.
Perf. note: this will scan the entire KV set of the plugin every time on startup. There is no "all is done, don't do it again" flag for the scan. @hanzei @catalintomai I don't really see it as an issue, but it's easy to persist the state (in a separate KV key?).

MM-34646: force-refresh user tokens

---

server/plugin/command.go
server/plugin/subscriptions.go
server/plugin/template.go
server/plugin/webhook.go

This PR adds a new feature which enables the user to subscribe only to see when Pull requests are merged and not when they are created, updated or labelled. For use case and other details, refer to #481.
Fixes https://github.com/mattermost/mattermost-plugin-github/issues/481

Feature: Subscribe to Merged PR's only.

---

server/plugin/command.go
server/plugin/plugin.go
server/plugin/subscriptions.go

Removed the convert logic which converts repo and org to lowercase
ticket here
Fixes #493

[issue - 493]Organization lock incorrectly validates against valid repos if org name is mixed case #493

---

Makefile
plugin.json
server/plugin/manifest.go
webapp/src/manifest.ts

Adding the linux/darwin arm64 targets, we start building arm64 for the server and will start adding the targets for the plugins for the ones we prepackage in the build
related to: https://github.com/mattermost/mattermost-server/pull/18491
related to https://mattermost.atlassian.net/browse/DOPS-633

dist: build linux/darwin arm64 targets

---

server/plugin/api.go
server/plugin/plugin.go
webapp/src/actions/index.js
webapp/src/components/sidebar_header/index.js
webapp/src/components/team_sidebar/index.js
webapp/src/index.js
webapp/src/reducers/index.js
webapp/src/selectors.js
webapp/src/websocket/index.js

> When a user fist logs into a Mattermost in a new browser they will not see the GitHub icons (connect or Pulls, Issues,Notifications etc..) on the LHS or team sidebar.
While initializing the plugin this method is called to fetch settings and get `left_sidebar_enabled`:
```javascript
await getSettings(store.getState);
```
But it fails if the user is not logged in, since auth is required to fetch settings for the plugin.
As you may observe, I handled that case so no HTTP requests to get settings will fail and load sidebar if the user is not logged in. Since at the time of initialization while user is not logged in, we don't have access to preferences for the plugin.
Resultant would be:
sidebar will load for the first time even if disabled if the user logs in for the first time.
- Why this …

GitHub LHS icon will not show on 1st login until the browser is refreshed

---

server/plugin/command.go

When using the `subscriptions add/delete` commands, the plugin did not correctly check the length of the parameters, causing the plugin to error when not specifying a repository. I fixed it :)
To reproduce, type one of the following into the chat with the GitHub plugin enabled:
- `/github subscriptions add`
- `/github subscriptions delete`
Fixes https://github.com/mattermost/mattermost-plugin-github/issues/520

[GH-520] Fix subscriptions add command parameter parsing error

---

server/plugin/flows.go

Fixed #535 by removing the `password` Subtype and replacing it with `text`.

Fixed #535: subtype is 'text' now

---

go.mod
go.sum
server/plugin/cluster.go
server/plugin/flows.go
server/plugin/oauth.go
server/plugin/webhook.go

If the plugin gets disabled while a reviving channel created by the broker is waiting for a message, a double `close` happens as the broker closes the channel and then the consumer closes it again in `UnsubscribeX`. Given that only the sender should close a channel, `UnsubscribeX` doesn't do that with this PR.
The PR also includes various other fixes.
None

Don't close message channel if client doesn't want to recive any longer

---

server/plugin/mm_34646_token_refresh.go
server/plugin/plugin.go

Removed racy in-line token refresh from githubConnect. 
Also:
- made sure that a cluster.Mutex is acquired before running the job
- added a KV "done" key to avoid repeating executions
#544

GH-544: Removed racy in-line token refresh from githubConnect

---

.golangci.yml
server/client/client.go
server/client/client_test.go
server/plugin/api_test.go
server/plugin/subscriptions.go
server/plugin/template.go

Fix linter errors caused by `golangci-lint` update
None

Fix linter errors

---

Makefile

Not longer needed as https://github.com/mattermost/circleci-orbs/pull/31 has been merged.
This PR should not be merged until a new release of the orb has been published.
Reverts mattermost/mattermost-plugin-github#577

Revert "Add --verbose flag to npm install"

---

.golangci.yml
Makefile
plugin.json
server/client/client.go
server/client/client_test.go
server/plugin/api_test.go
server/plugin/subscriptions.go
server/plugin/template.go
webapp/webpack.config.js

- https://github.com/mattermost/mattermost-plugin-github/pull/586
- https://github.com/mattermost/mattermost-plugin-github/pull/590
https://github.com/mattermost/mattermost-plugin-github/issues/588

Release 2.1.3

---

server/plugin/api.go

Fixes https://github.com/mattermost/mattermost-plugin-github/issues/605

Change OAuth complete timeout to 2 minutes

---

server/plugin/permalinks.go
server/plugin/permalinks_test.go

Handle relative paths in permalinks
https://mattermost.atlassian.net/browse/MM-51245

[MM-51245] Handle relative paths in permalinks

---

server/plugin/flows.go
server/plugin/telemetry.go

Previously errors returned from the telemetry tracker didn't get logged. This PR adds proper log messages for all errors the telemetry tracker returns.
https://mattermost.atlassian.net/browse/MM-51269m

[MM-51269] Log errors from telemetry events

---

go.mod
go.sum
server/plugin/api.go
server/plugin/configuration.go
server/plugin/plugin.go
server/plugin/telemetry.go

Requires https://github.com/mattermost/mattermost-plugin-api/pull/129 merge.
plugin-api version is hardcoded in the go.sum to the parent folder until we merge/release pluginapi (not expected to be merged as is).
It places telemetry client and tracker initialization together at onActivate and uses the new enable/disable commands at onConfigurationChange.
Also, pass a logger to the telemetry tracker when ServiceSettings.EnableDeveloper is true (through NewTelemetryTracker), which will end up logging the telemetry activity (no matter if the tracking config or client is disabled). This is still 2/5 until backwards-compatibility details are discussed.
Added event account_connected when we have a oauth successful connection (through setup or plain connect).
Fixes …

keep telemetry init together and do the enable/disable thing

---

build/custom.mk

After some name changing, MM_RUDDER_WRITE_KEY has become MM_RUDDER_PLUGINS_PROD.
Fix custom.mk so we get the right data.
nope

New secret rudder

---

Makefile

Simplify `make server` command by setting a new var for gcflags based on MM_DEBUG.
it was an opportunistic improvement while checking the current tooling.
Nope

move debug gcflags to a new var and remove one block on server build

---

server/plugin/api.go

**Summary** 
- When the Organization lock is set to a user's workspace rather than an organization, the create and attach modal will not show any results, so fix that by getting the data for the username as well.
- [Issue #548](https://github.com/mattermost/mattermost-plugin-github/issues/548)

[GH-548]:Fixed issue #548 on github 'org lock for username not working' 

---

server/plugin/flows.go
server/plugin/plugin.go
server/plugin/utils.go
server/plugin/utils_test.go

I'm unable to reproduce the issue linked in the ticket.
To debug the issue if it occurs again, I've added debug information on why exactly the wizard didn't run.
If the PR gets approved, I'm going to copy the change into https://github.com/mattermost/mattermost-plugin-gitlab.
https://mattermost.atlassian.net/browse/MM-42918

[MM-42918] Add debug information for setup wizard

---

.github/workflows/playwright.yml

Playwright tests are currently failing for fork PRs. This PR solves this by running the workflow alongside the `ci` workflow, to access variables for the Mattermost project during the workflow run.
Context https://community.mattermost.com/core/pl/buyo3qkq8tdm9yeobg6dsih4gy
Fixes https://mattermost.atlassian.net/browse/MM-53014

Make playwright tests run off of ci workflow run

---

server/plugin/webhook.go

**Summary** 
- Fixed the issue that When Pull Request Reviews are submitted (Comment, Approve, Change Requested), no message was appearing in the subscribed channel.
- [Issue #686](https://github.com/mattermost/mattermost-plugin-github/issues/686)

[GH-686]:Fixed issue #686 'Pull Request Reviews are not posted'

---

server/plugin/webhook.go

Fixed the improper formatting of special characters inside the code block of issue-created channel notifications.
- Special characters are properly displayed inside the code block present in the description of the issue-created notification.
Earlier:
Now:
Fixes #692

[GH-692] Fix formatting inside code block in issue created notification

---

plugin.json
server/plugin/webhook.go

- https://github.com/mattermost/mattermost-plugin-github/pull/697

Bump version to 2.1.7

---

server/plugin/plugin.go
server/plugin/utils.go
server/plugin/utils_test.go

The URL that was used to create the pretext of the unread message and the repo URL was missing in the body of Discussion and CheckSuite type unread. We updated the code to use the repo link present in the body of an unread message. Also, we couldn't find any possible way to get the URL of "Discussion" or "CheckSuite", so we are not displaying them as a link.
Earlier:
Now:
- If for some specific/unknown type of notification, the repo link is not present it might not be displayed properly.
- Links in the response of the `/github todo` command are rendered and working properly.
1. Connect your Github account to MM.
2. Create notifications of different types on Github, Like Discussion, checkSuite, PullRequest, etc.
3. Run the `/github todo` command in any MM channel.
MM version: v7.8.2
Node …

[GH-693] Fix improper rendering of some unreads in the response of "/github todo" command

---

server/plugin/template.go
server/plugin/template_test.go
server/plugin/webhook.go

- Added logic to handle the case for pull request reopened webhook event.
- Subscription notification for pull request reopened event is working properly.
1. Connect your GitHub account.
2. Create a subscription of event type "pulls" in a channel.
3. Reopen a closed PR on GitHub for the project you have created a subscription for.
- You should get a notification in the channel with the text similar to the above screenshot.
MM version: v9.2.2
Node version: 14.18.0
Go version: 1.20.11
Fixes #717

[GH-717] Implement subscription notification for pull request "reopened" event

---

plugin.json
server/plugin/template.go
server/plugin/template_test.go
server/plugin/webhook.go

- https://github.com/mattermost/mattermost-plugin-github/pull/718

Release 2.1.8

---

server/plugin/graphql/lhs_query.go
server/plugin/graphql/lhs_request.go
server/plugin/plugin.go
webapp/src/components/sidebar_right/github_items.tsx

1. Mention notifications not working.
2. Labels and milestones not displayed in the RHS.
- Labels and milestones are properly displayed in the RHS.
- Getting DM notifications for mentions.
- Labels and milestones:
1. Connect your GitHub account.
2. Create a PR on Github and add labels/milestones to it.
3. Open RHS for open PRs on Mattermost.
- DM notification:
1. Connect your GitHub account.
2. Create a webhook.
3. You should get notified in GitHub bot DM when someone else mentions/assigns you in a PR/Issue.
N/A

[MM-17] Fix issues in release 2.2.0

---

plugin.json
server/plugin/configuration.go
server/plugin/template.go
server/plugin/template_test.go
server/plugin/webhook.go

Pushed commits events: add option to show Author instead of Committer.
Before starting, some Mattermost channel should be subscribed to pushed commits notifications for a repo.
1. Go to plugin settings and set "Pushed commits events: show Author instead of Committer:" to true.
1. Create a git commit with committer != author. For example, "git am" a patch from someone else, or "git commit --author 'Test author <test@example.com>'" (example: https://github.com/FOULAB/eigma-test/commit/65ed77834f659a0498c5d02cc319e38bd12c50f3)
2. Push commit to GitHub
3. Observe the pushed commits notification.
Fixes https://github.com/mattermost/mattermost-plugin-github/issues/719

[GH-719] Pushed commits events: add option to show Author instead of committer

---

plugin.json

- https://github.com/mattermost/mattermost-plugin-github/issues/470
- https://github.com/mattermost/mattermost-plugin-github/pull/606
- https://github.com/mattermost/mattermost-plugin-github/pull/628
- https://github.com/mattermost/mattermost-plugin-github/pull/598
- https://github.com/mattermost/mattermost-plugin-github/issues/500
- https://github.com/mattermost/mattermost-plugin-github/pull/462
- https://github.com/mattermost/mattermost-plugin-github/issues/558
- https://github.com/mattermost/mattermost-plugin-github/pull/656
- https://github.com/mattermost/mattermost-plugin-github/issues/548
- https://github.com/mattermost/mattermost-plugin-github/pull/648
- https://github.com/mattermost/mattermost-plugin-github/pull/671
- https://github.com/mattermost/mattermost-plugin-github/pull/679 …

Bump version to 2.2.0.

---

server/plugin/command.go
server/plugin/webhook.go

- Updated the "issue_creations" subscription to post a notification when an issue is labeled/reopened
- Notification is getting posted when an existing issue is labeled in a channel with a subscription for `issue_creations,label:"label-name"`
- Notification is posted when an issue is reopened  in a channel with a subscription for `issue_creations`
1. Connect your GitHub account
2. Create a subscription for `issue_creations,label:"label-name"` is a channel.
3. Add a label (same as present in the subscription) to an existing issue.
Fixes #733

[GH-733] Updated the "issue_creations" subscription to post notification when an issue is labeled/reopened

---

.github/workflows/playwright.yml

The playwright test are currenly failing on `master` with `go: go.mod file indicates go 1.21, but maximum version supported by tidy is 1.19`. (https://github.com/mattermost/mattermost-plugin-github/actions/runs/8134028209/job/22226371191) Let's bump the go version there and see if that fixes things.
NONE

Bump go version for playwright test

---

client/client.go
go.mod
go.sum
server/plugin/api.go
server/plugin/cluster.go
server/plugin/command.go
server/plugin/flows.go
server/plugin/graphql/lhs_request.go
server/plugin/mm_34646_token_refresh.go
server/plugin/permalinks.go
server/plugin/permalinks_test.go
server/plugin/plugin.go
server/plugin/subscriptions.go
server/plugin/template.go
server/plugin/template_test.go
server/plugin/utils.go
server/plugin/utils_test.go
server/plugin/webhook.go

This PR bumps up the major version of the [google/go-github](https://github.com/google/go-github) dependency from v41 to [v54](https://github.com/google/go-github/releases/tag/v54.0.0).
While this isn't the latest version, it is the first version that introduces support for the [Projects v2 API](https://docs.github.com/en/webhooks/webhook-events-and-payloads#projects_v2) that could be used in creating subscriptions https://github.com/mattermost/mattermost-plugin-github/issues/409.
The only breaking change I could identify was the use of a [new wrapper datatype Timestamp](https://github.com/google/go-github/pull/2646), where previously time.Time was being used.
I don't have my E2E tests setup locally yet but can review the CI run when a maintainer allows it.

Updates go-github to v54 for projects v2 support

---

plugin.json

Using the hoisting property the UsePreregisteredApplication will only be on cloud servers.
https://github.com/mattermost/mattermost-plugin-github/issues/647
The UsePreregisteredApplication will be hidden in on-prem servers and can only be seen in cloud instances.

[GH-647]: Hide UsePreregisteredApplication on on-prem instances

---

README.md
server/plugin/command.go
server/plugin/subscriptions.go
server/plugin/template.go
server/plugin/template_test.go
server/plugin/webhook.go

- Added feature to publish release create and delete events
Fixes #723 
- Update the webhook for the repo to receive notifications for release events
- Create a subscription for a repo with a subscription enabled for release events
- Create and delete a release on the subscribed repo
- Check for the events received in the subscribed channel

[MM-352] Add feature to publish release create and delete events

---

server/plugin/command.go

- Update subscription message when user is not authorized to access webhooks
- Update subscription message when there is no webhook present
- When user is not authorized to access webhooks
- When there is no webhook present
Fixes https://github.com/mattermost/mattermost-plugin-github/issues/715
Fixes https://github.com/mattermost/mattermost-plugin-github/issues/732
- Create a subscription with the user who doesn't have access to create webhooks and verify the post
- Similarly, create a subscription with no prior webhook present and verify the post

Update subscription messages with respect to webhook

---

server/plugin/permalinks.go
server/plugin/permalinks_test.go
server/plugin/plugin.go

- Update code to show code preview for permalink with branch names
- Getting code preview for permalinks with branch names
1. Connect your GitHub account
2. Open a file on  a GitHub repo
3. Click on any line *number* in the file
4. Copy the browser URL
5. Post the link in the channel
- You should get a preview of the code near that permalink.
Fixes #670

[GH-670] Fix issue: Code previews not working for branches

---

server/plugin/plugin.go

Removed the log 'Emoji is not supported by Github' as it was coming every time any user added or removed the reaction on the post.
#805

[MM-805]: Removed the 'Emoji is not supported by Github' log from the reactions hooks

---

server/plugin/utils.go

- Added escape characters to user, repo and path in permalink preview to avoid repo/file name being rendered as markdown.
1. Connect your github account.
1. Paste the permalink of a file/repo with the name containing markdown pattern (Ex. \_\_abc\_\_ will be rendered as __abc__ in markdown)
Fixes #793

[MM-593] Added escape characters to user, repo and path in permalink preview

---

server/plugin/template.go

Fixed the issue of the wrong name shown in the subscription when PR is moved from draft to ready for review
Fixes https://github.com/mattermost/mattermost-plugin-github/issues/813
- Create a subscription for a repo
- Create a PR with user B and mark it as `draft`
- Mark the PR as `ready for review` from user A
`#new-pull-request by B`
`#new-pull-request by A`

MM-813: Fixed the issue of wrong name shown in subscription when PR is moved from draft to ready for review

---

server/plugin/api.go
server/plugin/command.go
server/plugin/flows.go
server/plugin/graphql/client.go
server/plugin/plugin.go
server/plugin/utils.go

https://github.com/mattermost/mattermost-plugin-github/pull/811 introduced a regression: The callback URL shown as part of the setup flow was missing the SiteURl.
This PR fixes the issue. On top of that, it unifies the handling of the SiteURL using two helper methods. 
https://mattermost.atlassian.net/browse/MM-60676

[MM-60676] Fix incorrect callback URL in setup flow

---

server/plugin/graphql/lhs_request.go

Fixed the issue of Github LHS not working if any organization is not set in the organization lock of the plugin config
- Check the data of LHS with and without organisation lock

[MM-874]: Fixed the issue of LHS not working without setting organisation lock

---

server/plugin/plugin.go
server/plugin/subscriptions.go

Made access to KV store atomically safe when saving/removing subscriptions by using `KV.SetAtomicWithRetries` in place of `KV.Set`
Fixes https://github.com/mattermost/mattermost-plugin-github/issues/141
- creation of subscription
- working of subscription
- deletion of working of subscription
Note: Keep on eye on the server logs while testing for any type of panic or error arising

[MM-141]: Made access to KV store atomically safe when saving/removing subscriptions

---

server/plugin/webhook.go

There is currently a bug described in the linked issue below. If both `pulls_created` and `pulls_merged` features are set for a subscription, any type of PR events are ignored.
I have fixed the `if` statement, and now it is possible to use both values and receive notifications for the respective event types.
Fixes https://github.com/mattermost/mattermost-plugin-github/issues/826

Fix missing PR notifications when using both pulls_created and pulls_merged features filter

---

webapp/src/components/github_repo_selector/github_repo_selector.jsx
webapp/src/components/modals/create_issue/create_issue.jsx
webapp/src/components/react_select_setting.jsx
webapp/src/components/setting.jsx

Fixes https://github.com/mattermost/mattermost-plugin-github/issues/497
Used inline style to avoid other possible changes to either 'error-text' or 'help-text'
Spaces now match the spacing between "Returns Github repositories....", "This field is required", and the fields themselves.
Edit: Accidentally linked wrong issue (498)

Fixes #497: "Validation Message spacing (UI) issue"

---

server/plugin/command_test.go

Added test cases for the following functions in command.go
- HandleSubscribe
- HandleSubscriptions
- GetCommand
- HandleHelp
- FormattedString
- ToSlice
https://github.com/mattermost/mattermost-plugin-github/pull/845

[MM-946]: Added testcases for some functions in command.go

---

go.mod
go.sum
server/plugin/support_packet.go
server/plugin/utils_test.go

When a Support Packet gets generated, the plugin now includes diagnostics data via a `diagnostics.yaml` file into the Packet.
Example content of `github/diagnostics.yaml`:
```yaml
version: 2.3.0+6ba0bcd
connected_user_count: 1
is_oauth_configured: true
```
Requires https://github.com/mattermost/mattermost/pull/28833 on the server side.
See https://mattermost.atlassian.net/wiki/spaces/CLOUD/pages/3083108354/Diagnostics+data+from+Core+Plugins+to+the+Support+Packet for more context.
https://mattermost.atlassian.net/browse/MM-61119

[MM-61118] Add diagnostics data to the Support Packet

---

server/plugin/template.go
server/plugin/webhook.go

Added a note to the subscription message post about the label of pr/issue if the subscription is specific to a label
Fixes https://github.com/mattermost/mattermost-plugin-github/issues/742
- Setup the plugin
- Create a subscription specific to a label
- Check the subscription post after creating a PR/Issue with the same label

[MM-742]: Added a note about the label of pr/issue if the subscription is specific to a label

---

server/plugin/template.go

Added the requested reviewers in the pulls_created notification
Fixes https://github.com/mattermost/mattermost-plugin-github/issues/856
- Create a subscription to a project
- Create a PR and add a reviewer to it
- Check the notifcation

[MM-856]: Added the requested reviewers in the pulls_created notification

---

webapp/src/components/modals/create_issue/create_issue.jsx

Removed default values from create_issue.jsx
Fixes https://github.com/mattermost/mattermost-plugin-github/issues/205

[MM-205]: removed default values from Input element in create_issue.jsx

---

server/plugin/test_utils.go

Added missing license header from `server/plugin/test_utils.go`

Fix broken CI on master

---

server/plugin/template.go
server/plugin/webhook.go

The discussion events were getting the same msg for "created", "closed" and "reopened" events and similarly for comment events. We updated it to include a custom message for each event.
BEFORE:
AFTER:

Fix discussion event notification

---

webapp/src/components/post_menu_action/create_issue/create_issue.jsx
webapp/src/components/post_menu_action/create_issue/index.js
webapp/src/components/post_menu_actions/attach_comment_to_issue/attach_comment_to_issue.jsx
webapp/src/components/post_menu_actions/attach_comment_to_issue/index.js
webapp/src/index.js

Remove depricated registerPostDropdownMenuComponent

Remove depricated registerPostDropdownMenuComponent

---

server/plugin/api.go
server/plugin/command.go
webapp/src/actions/index.ts
webapp/src/client/client.ts
webapp/src/components/github_repo_selector/github_repo_selector.jsx
webapp/src/components/github_repo_selector/index.js

- Fixed default repo functionality
- Fix check for username while muting
Fixes https://github.com/mattermost/mattermost-plugin-github/issues/933

Fixed default repo functionality and improve mute user functionality
